services:
  db:
    image: postgres:16
    container_name: test-leaderboard-db
    restart: always
    environment:
      POSTGRES_DB: leaderboards_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata_test:/var/lib/postgresql/data
      - ./src/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: test-leaderboard-api
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: leaderboards_test
      API_PORT: 8080
      STEAM_API_KEY: ${STEAM_API_KEY}
      STEAM_APP_ID: ${STEAM_APP_ID}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "8080:8080"

volumes:
  pgdata_test: